name: MyPy 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
            enable-cache: true
      
      - name: Install the project
        run: uv sync --dev --all-extras

      - name: Run MyPy type checking
        run: uv run mypy app --explicit-package-bases --pretty --show-error-codes